//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAisoV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int UserId { get; set; }
        public int StationeryId { get; set; }
        public int Quantity { get; set; }
    
        public virtual MsStationery MsStationery { get; set; }
        public virtual MsUser MsUser { get; set; }
    }
}
